# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-08 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0002_auto_20170408_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='authors',
            field=models.CharField(max_length=500),
        ),
    ]
